---
- name: Atualização do Sistema
  hosts: all
  tasks:
  - name: Upgrade OS (apt-get upgrade)
    ansible.builtin.apt:
      upgrade: dist
      force_apt_get: yes
#      upgrade: "{{ upgrade_mode }}"
      update_cache: yes
      install_recommends: yes
      autoremove: yes
#      cache_valid_time: 3600
# Para pacotes
#  - name: Only upgrade a package if it is already installed.
#    ansible.builtin.apt:
#      only_upgrade: yes
