---
- name: Atualização do Sistema
  hosts: all
  tasks:
  - name: Upgrade the OS (apt-get dist-upgrade), Only run "update_cache=yes" if the last one is more than 3600 seconds ago
    ansible.builtin.apt:
      upgrade: "{{ upgrade_mode }}"
      update_cache: yes
      install_recommends: yes
      autoremove: yes
#      cache_valid_time: 3600
# Para pacotes
#  - name: Only upgrade a package if it is already installed.
#    ansible.builtin.apt:
#      only_upgrade: yes
