---
- name: Configuração de acesso ao serviço de SSH
  hosts: all
  tasks:
  - name: 5.3.1 Verificando se as permissões do arquivo /etc/ssh/sshd_config estão corretas
    file:
      dest: /etc/ssh/sshd_config
      state: file
      owner: root
      group: root
      mode: 0600
  # Restringindo quais usuários podem acessar remotamente o sistema via SSH, somente usuarios autorizados.
  - name: 5.3.4 Verificando se o acesso ao SSH está limitado
    block:
      - name: 5.3.4  Verificando se o acesso por USUARIOS ao SSH está limitado | allow users
        lineinfile:
          state: present
          dest: /etc/ssh/sshd_config
          regexp: "^AllowUsers"
          line: "AllowUsers {{ allowed_users }}"
        when:
          - allowed_users != "None"
      - name: 5.3.4 Verificando se o acesso por GRUPOS ao SSH está limitad | allow groups
        lineinfile:
          state: present
          dest: /etc/ssh/sshd_config
          regexp: "^AllowGroups"
          line: "AllowGroups {{ allowed_groups }}"
        when:
          - allowed_groups != "None"
      - name: 5.3.4 Ensure SSH access is limited | denyusers
        lineinfile:
          state: present
          dest: /etc/ssh/sshd_config
          regexp: "^DenyUsers"
          line: "DenyUsers {{ deny_users }}"
        when:
          - deny_users != "None"
      - name: 5.3.4 Ensure SSH access is limited | denygroups
        lineinfile:
          state: present
          dest: /etc/ssh/sshd_config
          regexp: "^DenyGroups"
          line: "DenyGroups {{ deny_groups }}"
        when:
          - deny_groups != "None"
