---
- name: Atualização do Sistema
  hosts: all
  tasks:
  - name: Upgrade OS DOIS (apt-get upgrade)
    ansible.builtin.apt:
      upgrade: full
      force_apt_get: yes
      update_cache: yes
      autoremove: yes
      cache_valid_time: 3600
  
  - name: Set timezone to America/Sao_Paulo
    community.general.timezone:
      name: America/Sao_Paulo      

  - name: Ajuste no NTP
    lineinfile:
      state: present
      dest: /etc/systemd/timesyncd.conf 
      regexp: "#NTP="
      line: "NTP=a.ntp.br b.ntp.br c.ntp.br"

  - name: Restart service timesyncd
    ansible.builtin.systemd:
      name: systemd-timesyncd.service
      state: restarted

  - name: Ajustando .bashrc
    block:
      - name: HISTSIZE=10000
        lineinfile:
          state: present
          dest: /root/.bashrc
          regexp: "^HISTSIZE=1000"
          line: "HISTSIZE=10000"
      - name: HISTFILESIZE=20000
        lineinfile:
          state: present
          dest: /root/.bashrc
          regexp: "^HISTFILESIZE=2000"
          line: "HISTFILESIZE=20000"
      - name: HISTTIMEFORMAT="[%Y/%m/%d %T] "
        lineinfile:
          state: present
          dest: /root/.bashrc
          line: "{{ timeformat }}"          
      - name: force_color_prompt=yes
        lineinfile:
          state: present
          dest: /root/.bashrc
          regexp: "^#force_color_prompt=yes"
          line: "force_color_prompt=yes"
      - name: PS1
        lineinfile:
          state: present
          dest: /root/.bashrc
          regexp: "^{{ ps2 }}"
          line: "{{ ps1 }}"
